import React from 'react';
import { Link } from 'react-router-dom';
import './homepage.css';
import { useNavigate } from 'react-router-dom';

const HomePage = () => {
    const token = localStorage.getItem('token');
    const navigate = useNavigate();
    
    if (token) {
        navigate('/dashboard');
    }

    return (
        <div className="home-page">
            <main className="hero">
                <h1>Build Workouts Faster</h1>
                <p>FitSaveAI.org is an AI-powered workout builder for building workouts fast.</p>
                <div className="cta-buttons">
                    <Link to="/login" className="btn btn-secondary">Sign In</Link>
                    <Link to="/register" className="btn btn-primary">Register</Link>
                </div>
                <div className="boxes-container">
                    <div className="box">
                        <h2>Chest Day</h2>
                        <p>Description of Chest workouts...</p>
                    </div>
                    <div className="box">
                        <h2>Arms</h2>
                        <p>Description of Arm workouts...</p>
                    </div>
                    <div className="box">
                        <h2>Legs</h2>
                        <p>Description of Legs workouts...</p>
                    </div>
                </div>
            </main>
            <section className="features">
                <div className="feature">
                    <h2>AI-Powered Plans</h2>
                    <p>Get personalized workout plans generated by our advanced AI algorithm.</p>
                </div>
                <div className="feature">
                    <h2>Track Your Progress</h2>
                    <p>Monitor your workout progress and stay motivated.</p>
                </div>
                <div className="feature">
                    <h2>Community Support</h2>
                    <p>Join our community and share your fitness journey.</p>
                </div>
            </section>
            <section className="testimonials">
                <h2>What Our Users Say</h2>
                <div className="testimonial">
                    <p>"FitSaveAI has transformed my workout routine!" - Alex</p>
                </div>
                <div className="testimonial">
                    <p>"The AI-generated plans are amazing." - Taylor</p>
                </div>
                <div className="testimonial">
                    <p>"I love the progress tracking feature!" - Jordan</p>
                </div>
            </section>
            <footer className="footer">
                <div className="footer-contact">
                    <p>Contact Us: something@fitsaverai.com</p>
                    <p>Phone: +1 234 567 890</p>
                </div>
                <div className="footer-cta">
                    <Link to="/register" className="btn btn-primary">Get Started</Link>
                </div>
            </footer>
        </div>
    );
};

export default HomePage;
